[[pass]]
host = "val09"
path = ''
cmd  = 'cd rib/; ./bench_server'

[[pass]]
host = "val08"
path = ''
cmd  = 'cd rib/; ./bench_client -client_name val08 -threads 12'

[[pass]]
host = "val10"
path = ''
cmd  = 'cd rib/; ./bench_client -client_name val10 -threads 12'